cc_library(
    name = "node",
    hdrs = ["node.h"],
    visibility = ["//lib/test:__pkg__"]
)

cc_library(
    name = "stack",
    hdrs = ["stack.h"],
    deps = ["node"],
    visibility = ["//lib/test:__pkg__"]
)