cc_test(
    name = "stack-test",
    srcs = ["stack-test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//lib:stack",
    ],
)

cc_test(
    name = "queue-test",
    srcs = ["queue-test.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "//lib:queue",
    ],
)